import type { Metadata } from "next";
import { Crimson_Pro, Open_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/commons/navbar/navbar";
import MainProvider from "@/components/commons/main-provider";
import Sidebar from "@/components/commons/navbar/sidebar";
import Footer from "@/components/commons/footer/footer";

const crimsonPro = Crimson_Pro({
  variable: "--font-crimson-pro",
  subsets: ["latin"],
});

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${crimsonPro.variable} ${openSans.variable} antialiased`}
      >
        <MainProvider>
          <div className="hidden lg:block">
            <Navbar />
          </div>
          <div className="lg:hidden">
            <Sidebar />
          </div>
          {children}
          <Footer />
        </MainProvider>
      </body>
    </html>
  );
}
